# Generated by Django 5.1.4 on 2024-12-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='question_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TF', 'True/False')], max_length=3),
        ),
    ]
